### ISSUE TITLE
Parameter constraint problem in Categorical distribution in Sample.py

### ISSUE THREAD

**Issue by ThomasHeap** [alan-ppl/alan_old#4]
https://github.com/alan-ppl/alan/blob/cb22f1c055b368d7dc8aa75db7c6a4c92e098724/alan/Sample.py#L359

This Categorical distribution can sometimes throw the following error:

```sh
ValueError: Expected parameter probs (Tensor of shape (...)) of distribution Categorical(probs: torch.Size(...)) to satisfy the constraint Simplex()
```

This might be due to numerical issues when drawing many samples.

If we are sure that the ```cond``` tensor is legit we could modify [dist.py](https://github.com/alan-ppl/alan/blob/main/alan/dist.py) to allow us to pass ```validate_args = False``` as in the [following](https://discuss.pytorch.org/t/distributions-categorical-fails-with-constraint-simplex-but-manual-check-passes/163209/4).

**Comment by ThomasHeap** [comment]
@LaurenceA 

This is happening a lot now when calling predictive_ll

```
Traceback (most recent call last):
  File "/home/thomas/Work/alan/examples/fast_ml_experiments/runner.py", line 85, in run_experiment
    pred_likelihood = model.predictive_ll(sample, N = cfg.training.pred_ll.num_pred_ll_samples, data_all=all_data, inputs_all=all_covariates)
  File "/home/thomas/Work/alan/alan/model.py", line 195, in predictive_ll
    trace_pred, N = self._predictive(sample, N, data_all, inputs_all, None)
  File "/home/thomas/Work/alan/alan/model.py", line 164, in _predictive
    post_samples = sample._importance_samples(N)
  File "/home/thomas/Work/alan/alan/Sample.py", line 367, in _importance_samples
    K_post_idxs[K] = sample_cond(marg, K, K_post_idxs, N)
  File "/home/thomas/Work/alan/alan/Sample.py", line 396, in sample_cond
    return Categorical(cond).sample(False, sample_dims=(N,))
  File "/home/thomas/Work/alan/alan/dist.py", line 135, in sample
    torch_dist = self.dist(**self.all_args)
  File "/home/thomas/.local/lib/python3.10/site-packages/torch/distributions/categorical.py", line 66, in __init__
    super(Categorical, self).__init__(batch_shape, validate_args=validate_args)
  File "/home/thomas/.local/lib/python3.10/site-packages/torch/distributions/distribution.py", line 56, in __init__
    raise ValueError(
ValueError: Expected parameter probs (Tensor of shape (300, 1000, 3)) of distribution Categorical(probs: torch.Size([300, 1000, 3])) to satisfy the constraint Simplex(), but found invalid values:
...
```

**Comment by ThomasHeap** [comment]
This is happening in:

https://github.com/alan-ppl/alan/blob/f8bc59cd24705a691caa87b52d31c0c3bb0d0640/alan/Sample.py#L358

Because sometimes ```cond``` doesn't sum to 1 along the ```K``` dimension.

Easy fix?:

```python
return Categorical(t.nn.functional.softmax(cond,dim=-1)).sample(False, sample_dims=(N,))
```

**Comment by LaurenceA** [comment]
Can you carefully investigate / think about this stuff before coming back
to me?

It isn't (or shouldn't be) because cond doesn't sum to 1:
https://pytorch.org/docs/stable/distributions.html#torch.distributions.categorical.Categorical

And is it really valid to take some numbers that should be probabilities
and softmax them???

**Comment by ThomasHeap** [comment]
From:

https://github.com/pytorch/pytorch/blob/master/torch/distributions/constraints.py

```python
class _Simplex(Constraint):
    """
    Constrain to the unit simplex in the innermost (rightmost) dimension.
    Specifically: `x >= 0` and `x.sum(-1) == 1`.
    """
    event_dim = 1

    def check(self, value):
        return torch.all(value >= 0, dim=-1) & ((value.sum(-1) - 1).abs() < 1e-6)
```
I've checked and they don't sum to 1.

I'll take a look and try to figure out why it doesn't sum to 1.

Edit:

It seems ```Categorical``` applys normalisation before checking the Simplex() requirement, but it can still fail its own requirement after this:

https://github.com/pytorch/pytorch/issues/87468

So if we could normalise the probabilities before passing them to categorical, and pass validate_args=False to categorical we might be able to avoid this problem.

**Comment by LaurenceA** [comment]
[image: image.png]

**Comment by ThomasHeap** [comment]
Whatever that image is isn't rendering for me, but per the edit I think the solution here is being able to pass validate_args=False to dists.

**Comment by LaurenceA** [comment]
```

In [*5*]: *import* *torch* *as* *t*


In [*6*]: dist = t.distributions.Categorical(t.ones(3))


In [*7*]: sample = dist.sample()


In [*8*]: sample

Out[*8*]: tensor(2)


In [*9*]: dist.log_prob(sample)

Out[*9*]: tensor(-1.0986)

```

**Comment by ThomasHeap** [comment]
Yeah I've acknowledged this, and I believe the issue is arising due to the normalisation being applied within the torch distribution and we need to turn off the validation there.

**Comment by ThomasHeap** [comment]
Float32 issue occurs when calling model.predictive_ll:

```
Traceback (most recent call last):
  File "/home/thomas/Work/alan/examples/fast_ml_experiments/runner_ml.py", line 90, in run_experiment
    pred_likelihood = model.predictive_ll(sample, N = cfg.training.pred_ll.num_pred_ll_samples, data_all=all_data, inputs_all=all_covariates)
  File "/home/thomas/Work/alan/alan/model.py", line 184, in predictive_ll
    trace_pred, N = self._predictive(sample, N, data_all, inputs_all, None)
  File "/home/thomas/Work/alan/alan/model.py", line 153, in _predictive
    post_samples = sample._importance_samples(N)
  File "/home/thomas/Work/alan/alan/Sample.py", line 328, in _importance_samples
    K_post_idxs[K] = sample_cond(marg, K, K_post_idxs, N)
  File "/home/thomas/Work/alan/alan/Sample.py", line 349, in sample_cond
    assert cond.dtype == t.float64
AssertionError
```

When removing this assertion the ```Simplex()``` error remains.

**Comment by ThomasHeap** [comment]
Ok having investigated this some more, I think you were right. 

Checking with 

```python
(t.count_nonzero(test_cond,-1) == 0).any()
```

The simplex error is always preceded by a cond where at least one of the prob vectors is all zero.

Can we just discard these samples?

**Comment by ThomasHeap** [comment]
Temporary fix for this:

Replace
https://github.com/alan-ppl/alan/blob/c02536ede571eae111dabec9b3c5203dae6eaec5/alan/Sample.py#L271

with:
```python
logps = [self.varname2logp[var_name].double() for var_name in var_names]
```

**Comment by ThomasHeap** [comment]
> Temporary fix for this:
> 
> Replace
> 
> https://github.com/alan-ppl/alan/blob/c02536ede571eae111dabec9b3c5203dae6eaec5/alan/Sample.py#L271
> 
> with:
> 
> ```python
> logps = [self.varname2logp[var_name].double() for var_name in var_names]
> ```

Ok this makes the problem better but having run other examples for more iterations the same error can still occur. 

Can we add some kind of try-except thing that draws another set of importance samples if this error occurs?

Edit: Interesting to note, this happens much more when training with mp VI than when I'm using the ml updates.
